source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.baijiahulian.com/app/specs.git'

target 'BJHL-IM-iOS-SDK' do
  pod "BJHL-IM-iOS-SDK", :path => "../"
end

target 'Tests' do
  pod "BJHL-IM-iOS-SDK", :path => "../"
  pod 'MagicalRecord'
end
